# Generated by Django 2.2.6 on 2019-10-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20191026_1321'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aspects',
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Equipo', 'verbose_name_plural': 'Equipos'},
        ),
        migrations.AlterModelOptions(
            name='userhistory',
            options={'verbose_name': 'Historia de usuario', 'verbose_name_plural': 'Historia de usuarios'},
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
    ]
