# Generated by Django 2.2.6 on 2019-11-04 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20191026_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='team',
            field=models.ForeignKey(help_text='Equipo al que pertenece el proyecto', on_delete=django.db.models.deletion.CASCADE, to='app.Team', verbose_name='Equipo'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(help_text='Nombre del equipo', max_length=200, verbose_name='Nombre'),
        ),
    ]
