# Generated by Django 2.2.6 on 2019-11-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20191117_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='manager_code',
            field=models.CharField(default='test', max_length=200, unique=True, verbose_name='código del gerente'),
        ),
        migrations.AlterField(
            model_name='project',
            name='planning_end_date',
            field=models.DateField(verbose_name='Fecha planeada de finalización'),
        ),
        migrations.AlterField(
            model_name='project',
            name='planning_start_date',
            field=models.DateField(verbose_name='Fecha planeada de inicio'),
        ),
        migrations.AlterField(
            model_name='project',
            name='real_end_date',
            field=models.DateField(verbose_name='Fecha real de finalización'),
        ),
        migrations.AlterField(
            model_name='project',
            name='real_start_date',
            field=models.DateField(verbose_name='Fecha real de inicio'),
        ),
    ]
