# Generated by Django 2.2.6 on 2019-11-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='email@demo.co', max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='salary',
            field=models.CharField(max_length=200, verbose_name='Salario'),
        ),
    ]
