# Generated by Django 2.2.6 on 2019-11-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20191117_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='manager_code',
            field=models.CharField(default='test', max_length=200, verbose_name='código del gerente'),
        ),
    ]
