# Generated by Django 2.2.7 on 2019-12-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='full_duration',
            field=models.IntegerField(default=0, verbose_name='Duración'),
        ),
    ]
