# Generated by Django 2.2.5 on 2019-09-10 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aspects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('history_type', models.TextField()),
                ('user', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('criteria_of_acceptance', models.TextField()),
                ('interface_requirements', models.TextField()),
                ('dependencies', models.TextField()),
            ],
        ),
    ]
