# Generated by Django 2.2.6 on 2019-10-26 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191026_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
            ],
        ),
        migrations.AlterField(
            model_name='team',
            name='user',
            field=models.ManyToManyField(help_text='Usuarios que hacen parte del equipo', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('history_type', models.TextField(verbose_name='Tipo de historia')),
                ('description', models.TextField(verbose_name='descripción')),
                ('criteria_of_acceptance', models.TextField(verbose_name='criterio de aceptación')),
                ('interface_requirements', models.TextField(verbose_name='requerimientos de interfaz')),
                ('dependencies', models.TextField(verbose_name='dependencias')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('project', models.ForeignKey(help_text='Proyecto al que pertenece la historia de usuario', on_delete=django.db.models.deletion.PROTECT, to='app.Project', verbose_name='Proyecto')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ForeignKey(help_text='Equipo al que pertenece el proyecto', on_delete=django.db.models.deletion.PROTECT, to='app.Team', verbose_name='Equipo'),
        ),
    ]
