# Generated by Django 2.2.6 on 2019-10-26 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20191026_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhistory',
            name='name',
        ),
    ]
