# Generated by Django 2.2.6 on 2019-10-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_userhistory_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhistory',
            name='title',
        ),
        migrations.AddField(
            model_name='userhistory',
            name='name',
            field=models.CharField(default='asd', max_length=200, verbose_name='Título'),
            preserve_default=False,
        ),
    ]
