# Generated by Django 2.2.6 on 2019-10-26 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20191026_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userhistory',
            old_name='name',
            new_name='title',
        ),
    ]
