# Generated by Django 2.2.6 on 2019-11-04 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20191104_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistory',
            name='project',
            field=models.ForeignKey(help_text='Proyecto al que pertenece la historia de usuario', on_delete=django.db.models.deletion.CASCADE, to='app.Project', verbose_name='Proyecto'),
        ),
    ]
