# Generated by Django 2.2.6 on 2019-11-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20191104_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='manager_code',
            field=models.CharField(default='test', max_length=200, unique=True, verbose_name='nombre del gerente'),
        ),
        migrations.AddField(
            model_name='project',
            name='manager_name',
            field=models.CharField(default='test', max_length=200, verbose_name='nombre del gerente'),
        ),
        migrations.AddField(
            model_name='project',
            name='planning_end_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha planeada de finalización'),
        ),
        migrations.AddField(
            model_name='project',
            name='planning_start_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha planeada de inicio'),
        ),
        migrations.AddField(
            model_name='project',
            name='real_end_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha real de finalización'),
        ),
        migrations.AddField(
            model_name='project',
            name='real_start_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha real de inicio'),
        ),
    ]
