# Generated by Django 2.2.6 on 2019-11-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20191117_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('charge', models.CharField(default='test', max_length=200, verbose_name='Cargo')),
                ('salary', models.CharField(default='test', max_length=200, verbose_name='Salario')),
                ('income_date', models.DateField(verbose_name='Fecha de ingreso')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
