# Generated by Django 2.2.6 on 2019-11-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20191117_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='name', max_length=200, verbose_name='nombre'),
        ),
    ]
