# Generated by Django 2.2.6 on 2019-11-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_user_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='team',
            name='user',
            field=models.ManyToManyField(help_text='Usuarios que hacen parte del equipo', to='app.User', verbose_name='Usuario'),
        ),
    ]
