# Generated by Django 2.2.6 on 2019-11-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20191117_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='email@demo.co', max_length=254, verbose_name='email address'),
        ),
    ]
