# Generated by Django 2.2.7 on 2019-12-01 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20191117_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='descripción')),
                ('duration', models.IntegerField(default=0, verbose_name='Duración')),
                ('project', models.ForeignKey(help_text='Proyecto al que pertenece la historia de usuario', on_delete=django.db.models.deletion.CASCADE, to='app.Project', verbose_name='Proyecto')),
                ('user', models.ForeignKey(help_text='Usuario que ejecuta la actividad', on_delete=django.db.models.deletion.CASCADE, to='app.User', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
            },
        ),
    ]
