# Generated by Django 2.2.7 on 2019-12-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_project_full_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='user',
        ),
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.ManyToManyField(help_text='Usuarios que realizaron la actividad', to='app.User', verbose_name='Usuario'),
        ),
    ]
